In [18]:
from treys import Card
from treys import Evaluator
from treys import Deck
import pickle

In [19]:
dict = pickle.load(open("dic1.pkl","rb"))

In [20]:
dict = pickle.load(open("dic1.pkl","rb"))
dict_hdb = pickle.load(open("dic3.pkl","rb"))

In [21]:
gamesRL3=[]
gamesRL4=[]
gamesRL5=[]
for i in dict:
    for j in range(len(dict[i])):
        gamesRL3.append([dict[i][j][2][:3],dict[i][j][10],dict[i][j][3],dict_hdb[dict[i][j][0]][0][4],dict[i][j][9]])
        gamesRL4.append([dict[i][j][2][:4],dict[i][j][10],dict[i][j][4],dict_hdb[dict[i][j][0]][0][5],dict[i][j][9]])
        gamesRL5.append([dict[i][j][2][:5],dict[i][j][10],dict[i][j][5],dict_hdb[dict[i][j][0]][0][6],dict[i][j][9]])

print(gamesRL3[7])
print(gamesRL4[7])
print(gamesRL5[7])

[['Ac', '2d', '5d'], ['As', '7s'], ['B', 'k'], '4/40', '1080']
[['Ac', '2d', '5d', 'Th'], ['As', '7s'], ['r'], '2/360', '1080']
[['Ac', '2d', '5d', 'Th', '9d'], ['As', '7s'], ['b'], '2/1080', '1080']


In [22]:
board = [Card.new(gamesRL5[7][0][i]) for i in range(5)]

In [23]:
evaluator = Evaluator()
evaluator.evaluate(board,[])
print(Card.print_pretty_cards(board))

 [A♣],[2♦],[5♦],[T♥],[9♦] 


In [24]:
table = []
y = []
for i in range(len(gamesRL3)):
    table.append([gamesRL3[i][2].count('r')+gamesRL3[i][2].count('b'),gamesRL3[i][2].count('c'),gamesRL3[i][2].count('k'),gamesRL3[i][2].count('B'),int(gamesRL3[i][3].split("/")[1])])
    y.append(evaluator.evaluate([Card.new(i) for i in gamesRL3[i][0]],[Card.new(i) for i in gamesRL3[i][1]]))

In [25]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [26]:
X = np.array(table)
Y = np.array(y)

In [35]:
model = Sequential()
# model.add(Dense(32, input_dim=5, activation='linear',kernel_initializer='normal'))
# model.add(Dense(8, activation='linear',kernel_initializer='normal'))
# model.add(Dense(4, activation='linear',kernel_initializer='normal'))
model.add(Dense(1,input_dim=5,kernel_initializer='normal'))

In [36]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics = ["mse"])

In [37]:
model.fit(X, Y, epochs=1000, batch_size=50)

Epoch 1/1000
3507/3507 [==============================] - 0s 134us/step - loss: 29607539.7177 - mean_squared_error: 29607539.7177
Epoch 2/1000
3507/3507 [==============================] - 0s 50us/step - loss: 29557666.8868 - mean_squared_error: 29557666.8868
Epoch 3/1000
3507/3507 [==============================] - 0s 47us/step - loss: 29507671.9738 - mean_squared_error: 29507671.9738
Epoch 4/1000
3507/3507 [==============================] - 0s 51us/step - loss: 29458108.0416 - mean_squared_error: 29458108.0416
Epoch 5/1000
3507/3507 [==============================] - 0s 50us/step - loss: 29408855.5483 - mean_squared_error: 29408855.5483
Epoch 6/1000
3507/3507 [==============================] - 0s 45us/step - loss: 29359291.8027 - mean_squared_error: 29359291.8027
Epoch 7/1000
3507/3507 [==============================] - 0s 45us/step - loss: 29310699.8911 - mean_squared_error: 29310699.8911
Epoch 8/1000
3507/3507 [==============================] - 0s 44us/step - loss: 29261905.7206 - m

3507/3507 [==============================] - 0s 58us/step - loss: 26849817.9059 - mean_squared_error: 26849817.9059
Epoch 65/1000
3507/3507 [==============================] - 0s 60us/step - loss: 26811477.5740 - mean_squared_error: 26811477.5740
Epoch 66/1000
3507/3507 [==============================] - 0s 74us/step - loss: 26773577.9718 - mean_squared_error: 26773577.9718
Epoch 67/1000
3507/3507 [==============================] - 0s 65us/step - loss: 26735909.8871 - mean_squared_error: 26735909.8871
Epoch 68/1000
3507/3507 [==============================] - 0s 58us/step - loss: 26698396.8121 - mean_squared_error: 26698396.8121
Epoch 69/1000
3507/3507 [==============================] - 0s 52us/step - loss: 26661102.7511 - mean_squared_error: 26661102.7511
Epoch 70/1000
3507/3507 [==============================] - 0s 39us/step - loss: 26623955.0328 - mean_squared_error: 26623955.0328
Epoch 71/1000
3507/3507 [==============================] - 0s 38us/step - loss: 26586836.6940 - mean_squ

3507/3507 [==============================] - 0s 45us/step - loss: 24819952.6096 - mean_squared_error: 24819952.6096
Epoch 127/1000
3507/3507 [==============================] - 0s 40us/step - loss: 24792808.3616 - mean_squared_error: 24792808.3616
Epoch 128/1000
3507/3507 [==============================] - 0s 41us/step - loss: 24765861.5689 - mean_squared_error: 24765861.5689
Epoch 129/1000
3507/3507 [==============================] - 0s 43us/step - loss: 24739929.2421 - mean_squared_error: 24739929.2421
Epoch 130/1000
3507/3507 [==============================] - 0s 40us/step - loss: 24713795.3111 - mean_squared_error: 24713795.3111
Epoch 131/1000
3507/3507 [==============================] - 0s 59us/step - loss: 24687710.5498 - mean_squared_error: 24687710.5498
Epoch 132/1000
3507/3507 [==============================] - 0s 69us/step - loss: 24661383.0910 - mean_squared_error: 24661383.0910
Epoch 133/1000
3507/3507 [==============================] - 0s 49us/step - loss: 24635362.6171 - m

3507/3507 [==============================] - 0s 50us/step - loss: 23512329.4388 - mean_squared_error: 23512329.4388
Epoch 189/1000
3507/3507 [==============================] - 0s 42us/step - loss: 23497316.9564 - mean_squared_error: 23497316.9564
Epoch 190/1000
3507/3507 [==============================] - 0s 42us/step - loss: 23482228.3222 - mean_squared_error: 23482228.3222
Epoch 191/1000
3507/3507 [==============================] - 0s 40us/step - loss: 23467146.0051 - mean_squared_error: 23467146.0051
Epoch 192/1000
3507/3507 [==============================] - 0s 40us/step - loss: 23452273.4719 - mean_squared_error: 23452273.4719
Epoch 193/1000
3507/3507 [==============================] - 0s 42us/step - loss: 23437292.4129 - mean_squared_error: 23437292.4129
Epoch 194/1000
3507/3507 [==============================] - 0s 41us/step - loss: 23422209.7439 - mean_squared_error: 23422209.7439
Epoch 195/1000
3507/3507 [==============================] - 0s 41us/step - loss: 23407555.9866 - m

3507/3507 [==============================] - 0s 48us/step - loss: 22773307.1158 - mean_squared_error: 22773307.1158
Epoch 251/1000
3507/3507 [==============================] - 0s 43us/step - loss: 22765632.4283 - mean_squared_error: 22765632.4283
Epoch 252/1000
3507/3507 [==============================] - 0s 42us/step - loss: 22757888.4488 - mean_squared_error: 22757888.4488
Epoch 253/1000
3507/3507 [==============================] - 0s 43us/step - loss: 22749895.9430 - mean_squared_error: 22749895.9430
Epoch 254/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22742358.1329 - mean_squared_error: 22742358.1329
Epoch 255/1000
3507/3507 [==============================] - 0s 43us/step - loss: 22734560.0741 - mean_squared_error: 22734560.0741
Epoch 256/1000
3507/3507 [==============================] - 0s 40us/step - loss: 22726971.4862 - mean_squared_error: 22726971.4862
Epoch 257/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22719213.1936 - m

3507/3507 [==============================] - 0s 51us/step - loss: 22381341.4098 - mean_squared_error: 22381341.4098
Epoch 313/1000
3507/3507 [==============================] - 0s 42us/step - loss: 22376922.0211 - mean_squared_error: 22376922.0211
Epoch 314/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22372325.7160 - mean_squared_error: 22372325.7160
Epoch 315/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22367824.1591 - mean_squared_error: 22367824.1591
Epoch 316/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22363153.7958 - mean_squared_error: 22363153.7958
Epoch 317/1000
3507/3507 [==============================] - 0s 42us/step - loss: 22358637.8951 - mean_squared_error: 22358637.8951
Epoch 318/1000
3507/3507 [==============================] - 0s 40us/step - loss: 22354046.1508 - mean_squared_error: 22354046.1508
Epoch 319/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22349659.2601 - m

3507/3507 [==============================] - 0s 44us/step - loss: 22146835.1086 - mean_squared_error: 22146835.1086
Epoch 375/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22143517.6270 - mean_squared_error: 22143517.6270
Epoch 376/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22140464.2281 - mean_squared_error: 22140464.2281
Epoch 377/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22138796.2435 - mean_squared_error: 22138796.2435
Epoch 378/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22135986.4451 - mean_squared_error: 22135986.4451
Epoch 379/1000
3507/3507 [==============================] - 0s 42us/step - loss: 22132881.0488 - mean_squared_error: 22132881.0488
Epoch 380/1000
3507/3507 [==============================] - 0s 41us/step - loss: 22129948.8668 - mean_squared_error: 22129948.8668
Epoch 381/1000
3507/3507 [==============================] - 0s 40us/step - loss: 22127285.0185 - m

3507/3507 [==============================] - 0s 34us/step - loss: 21981372.6929 - mean_squared_error: 21981372.6929
Epoch 437/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21979039.1731 - mean_squared_error: 21979039.1731
Epoch 438/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21976576.3279 - mean_squared_error: 21976576.3279
Epoch 439/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21974163.0699 - mean_squared_error: 21974163.0699
Epoch 440/1000
3507/3507 [==============================] - 0s 51us/step - loss: 21971833.4896 - mean_squared_error: 21971833.4896
Epoch 441/1000
3507/3507 [==============================] - 0s 73us/step - loss: 21969352.1374 - mean_squared_error: 21969352.1374
Epoch 442/1000
3507/3507 [==============================] - 0s 57us/step - loss: 21967177.3875 - mean_squared_error: 21967177.3875
Epoch 443/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21964649.1577 - m

3507/3507 [==============================] - 0s 68us/step - loss: 21852499.6401 - mean_squared_error: 21852499.6401
Epoch 499/1000
3507/3507 [==============================] - 0s 62us/step - loss: 21850549.1497 - mean_squared_error: 21850549.1497
Epoch 500/1000
3507/3507 [==============================] - 0s 65us/step - loss: 21848585.4571 - mean_squared_error: 21848585.4571
Epoch 501/1000
3507/3507 [==============================] - 0s 89us/step - loss: 21846792.8965 - mean_squared_error: 21846792.8965
Epoch 502/1000
3507/3507 [==============================] - 0s 69us/step - loss: 21845131.1161 - mean_squared_error: 21845131.1161
Epoch 503/1000
3507/3507 [==============================] - 0s 55us/step - loss: 21843009.2364 - mean_squared_error: 21843009.2364
Epoch 504/1000
3507/3507 [==============================] - 0s 46us/step - loss: 21841204.0662 - mean_squared_error: 21841204.0662
Epoch 505/1000
3507/3507 [==============================] - 0s 47us/step - loss: 21839184.5107 - m

3507/3507 [==============================] - 0s 35us/step - loss: 21744078.3861 - mean_squared_error: 21744078.3861
Epoch 561/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21742383.9344 - mean_squared_error: 21742383.9344
Epoch 562/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21740706.0687 - mean_squared_error: 21740706.0687
Epoch 563/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21739129.7268 - mean_squared_error: 21739129.7268
Epoch 564/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21737521.3399 - mean_squared_error: 21737521.3399
Epoch 565/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21735848.0890 - mean_squared_error: 21735848.0890
Epoch 566/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21734265.2096 - mean_squared_error: 21734265.2096
Epoch 567/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21732798.5492 - m

3507/3507 [==============================] - 0s 34us/step - loss: 21648392.2270 - mean_squared_error: 21648392.2270
Epoch 623/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21647797.5064 - mean_squared_error: 21647797.5064
Epoch 624/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21645964.2053 - mean_squared_error: 21645964.2053
Epoch 625/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21644551.1377 - mean_squared_error: 21644551.1377
Epoch 626/1000
3507/3507 [==============================] - 0s 36us/step - loss: 21643199.0339 - mean_squared_error: 21643199.0339
Epoch 627/1000
3507/3507 [==============================] - 0s 36us/step - loss: 21641557.3345 - mean_squared_error: 21641557.3345
Epoch 628/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21640082.0659 - mean_squared_error: 21640082.0659
Epoch 629/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21638674.1651 - m

3507/3507 [==============================] - 0s 70us/step - loss: 21560344.3861 - mean_squared_error: 21560344.3861
Epoch 685/1000
3507/3507 [==============================] - 0s 63us/step - loss: 21559009.5934 - mean_squared_error: 21559009.5934
Epoch 686/1000
3507/3507 [==============================] - 0s 52us/step - loss: 21557606.9806 - mean_squared_error: 21557606.9806
Epoch 687/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21556086.2093 - mean_squared_error: 21556086.2093
Epoch 688/1000
3507/3507 [==============================] - 0s 51us/step - loss: 21554698.8229 - mean_squared_error: 21554698.8229
Epoch 689/1000
3507/3507 [==============================] - 0s 60us/step - loss: 21553386.2572 - mean_squared_error: 21553386.2572
Epoch 690/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21551978.7881 - mean_squared_error: 21551978.7881
Epoch 691/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21550820.3353 - m

3507/3507 [==============================] - 0s 35us/step - loss: 21475452.8235 - mean_squared_error: 21475452.8235
Epoch 747/1000
3507/3507 [==============================] - 0s 36us/step - loss: 21474006.8651 - mean_squared_error: 21474006.8651
Epoch 748/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21472738.7733 - mean_squared_error: 21472738.7733
Epoch 749/1000
3507/3507 [==============================] - 0s 38us/step - loss: 21471390.2820 - mean_squared_error: 21471390.2820
Epoch 750/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21470160.1631 - mean_squared_error: 21470160.1631
Epoch 751/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21468780.6684 - mean_squared_error: 21468780.6684
Epoch 752/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21467526.7710 - mean_squared_error: 21467526.7710
Epoch 753/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21466016.1620 - m

3507/3507 [==============================] - 0s 35us/step - loss: 21393014.9347 - mean_squared_error: 21393014.9347
Epoch 809/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21391592.0157 - mean_squared_error: 21391592.0157
Epoch 810/1000
3507/3507 [==============================] - 0s 41us/step - loss: 21390602.5731 - mean_squared_error: 21390602.5731
Epoch 811/1000
3507/3507 [==============================] - 0s 39us/step - loss: 21389040.2697 - mean_squared_error: 21389040.2697
Epoch 812/1000
3507/3507 [==============================] - 0s 36us/step - loss: 21387838.3097 - mean_squared_error: 21387838.3097
Epoch 813/1000
3507/3507 [==============================] - 0s 41us/step - loss: 21386630.0413 - mean_squared_error: 21386630.0413
Epoch 814/1000
3507/3507 [==============================] - 0s 43us/step - loss: 21385371.4662 - mean_squared_error: 21385371.4662
Epoch 815/1000
3507/3507 [==============================] - 0s 41us/step - loss: 21383887.0858 - m

3507/3507 [==============================] - 0s 80us/step - loss: 21311777.7593 - mean_squared_error: 21311777.7593
Epoch 871/1000
3507/3507 [==============================] - 0s 67us/step - loss: 21310570.6496 - mean_squared_error: 21310570.6496
Epoch 872/1000
3507/3507 [==============================] - 0s 79us/step - loss: 21309337.6302 - mean_squared_error: 21309337.6302
Epoch 873/1000
3507/3507 [==============================] - 0s 79us/step - loss: 21307997.6527 - mean_squared_error: 21307997.6527
Epoch 874/1000
3507/3507 [==============================] - 0s 70us/step - loss: 21306573.3236 - mean_squared_error: 21306573.3236
Epoch 875/1000
3507/3507 [==============================] - 0s 66us/step - loss: 21305618.5326 - mean_squared_error: 21305618.5326
Epoch 876/1000
3507/3507 [==============================] - 0s 78us/step - loss: 21304021.6068 - mean_squared_error: 21304021.6068
Epoch 877/1000
3507/3507 [==============================] - 0s 84us/step - loss: 21302810.8010 - m

3507/3507 [==============================] - 0s 38us/step - loss: 21231798.9604 - mean_squared_error: 21231798.9604
Epoch 933/1000
3507/3507 [==============================] - 0s 35us/step - loss: 21230311.7017 - mean_squared_error: 21230311.7017
Epoch 934/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21229399.4485 - mean_squared_error: 21229399.4485
Epoch 935/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21227743.7228 - mean_squared_error: 21227743.7228
Epoch 936/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21226468.3023 - mean_squared_error: 21226468.3023
Epoch 937/1000
3507/3507 [==============================] - 0s 34us/step - loss: 21225197.9224 - mean_squared_error: 21225197.9224
Epoch 938/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21223926.8743 - mean_squared_error: 21223926.8743
Epoch 939/1000
3507/3507 [==============================] - 0s 33us/step - loss: 21222619.1497 - m

3507/3507 [==============================] - 0s 40us/step - loss: 21152263.0756 - mean_squared_error: 21152263.0756
Epoch 995/1000
3507/3507 [==============================] - 0s 40us/step - loss: 21150689.6764 - mean_squared_error: 21150689.6764
Epoch 996/1000
3507/3507 [==============================] - 0s 41us/step - loss: 21149462.1431 - mean_squared_error: 21149462.1431
Epoch 997/1000
3507/3507 [==============================] - 0s 41us/step - loss: 21148195.7930 - mean_squared_error: 21148195.7930
Epoch 998/1000
3507/3507 [==============================] - 0s 37us/step - loss: 21147099.8982 - mean_squared_error: 21147099.8982
Epoch 999/1000
3507/3507 [==============================] - 0s 38us/step - loss: 21145608.8751 - mean_squared_error: 21145608.8751
Epoch 1000/1000
3507/3507 [==============================] - 0s 36us/step - loss: 21144301.4343 - mean_squared_error: 21144301.4343


In [13]:
X_test = [[0,1,1,0,560]]
X_test = np.array(X_test)

In [33]:
predictions = model.predict(X)
for i in range(len(X)):
    print(X[i],predictions[i])

[  1   0   0   0 110] [4996.897]
[ 0  1  0  0 70] [5166.4526]
[ 0  1  0  0 40] [5200.648]
[  0   1   0   1 105] [5097.3433]
[ 0  1  0  0 45] [5194.9487]
[ 0  1  0  1 40] [5171.434]
[  1   0   0   0 285] [4797.422]
[ 0  0  1  1 40] [5484.2085]
[ 0  0  1  1 30] [5495.607]
[ 0  1  0  0 40] [5200.648]
[ 0  1  0  0 45] [5194.9487]
[ 0  1  0  0 60] [5177.851]
[ 0  0  1  1 30] [5495.607]
[  1   0   0   0 180] [4917.1064]
[  1   0   0   0 220] [4871.512]
[ 0  1  0  0 30] [5212.047]
[ 0  1  0  0 25] [5217.7466]
[ 0  0  1  1 30] [5495.607]
[ 0  1  0  0 30] [5212.047]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  1 75] [5131.5386]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  1 75] [5131.5386]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 60] [5148.637]
[ 1  0  0  0 80] [5031.0923]
[ 0  2  0  1 50] [5108.954]
[ 0  0  1  1 20] [5507.0054]
[ 1  0  0  1 60] [5024.6753]
[ 0  1  0  0 25] [5217.7466]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  

[  0   2   0   0 170] [5001.3853]
[ 0  1  0  0 60] [5177.851]
[ 0  1  0  1 70] [5137.2383]
[ 0  1  0  0 80] [5155.054]
[ 0  1  0  0 50] [5189.25]
[ 0  1  0  0 70] [5166.4526]
[ 0  1  0  0 40] [5200.648]
[ 0  0  1  1 60] [5461.4106]
[ 0  1  0  0 60] [5177.851]
[ 0  1  0  0 70] [5166.4526]
[  0   1   0   0 240] [4972.6763]
[ 0  1  0  0 55] [5183.5503]
[ 0  0  1  1 70] [5450.0127]
[ 0  1  0  0 70] [5166.4526]
[ 0  1  0  0 40] [5200.648]
[ 0  1  0  0 50] [5189.25]
[ 0  1  0  0 60] [5177.851]
[ 0  1  0  0 60] [5177.851]
[ 0  1  0  1 40] [5171.434]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  0 40] [5200.648]
[ 0  0  1  1 30] [5495.607]
[ 0  1  0  0 85] [5149.355]
[ 0  2  0  0 90] [5092.5747]
[ 0  1  0  1 70] [5137.2383]
[ 0  1  0  0 45] [5194.9487]
[ 0  1  0  0 30] [5212.047]
[ 0  1  0  0 70] [5166.4526]
[ 0  1  0  0 50] [5189.25]
[ 0  1  0  0 40] [5200.648]
[  0   2   0   0 140] [5035.5815]
[ 0  0  1  1 30] [5495.607]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  0 50] [5189.25]
[  0   2   0   0 105] 

[ 0  1  0  1 30] [5182.8325]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  1 30] [5182.8325]
[  0   1   0   1 475] [4675.5947]
[ 0  1  0  1 60] [5148.637]
[ 0  0  1  1 30] [5495.607]
[ 1  0  0  1 90] [4990.4795]
[ 1  0  0  0 80] [5031.0923]
[ 1  0  0  0 85] [5025.393]
[  1   0   0   0 255] [4831.6167]
[ 0  0  1  1 25] [5501.306]
[ 0  1  0  0 40] [5200.648]
[  1   0   0   0 230] [4860.1133]
[ 0  1  0  1 30] [5182.8325]
[ 0  1  0  1 30] [5182.8325]
[  1   1   0   0 180] [4866.0254]
[  1   0   0   0 225] [4865.813]
[ 0  1  0  1 50] [5160.0356]
[ 0  1  0  1 70] [5137.2383]
[ 0  1  0  0 60] [5177.851]
[  1   0   0   0 680] [4347.1772]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  1 30] [5182.8325]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 40] [5484.2085]
[  1   0   0   0 105] [5002.596]
[ 0  1  0  0 40] [5200.648]
[ 1  0  0  0 75] [5036.7925]
[  1   0   0   1 

[  0   2   0   0 200] [4967.19]
[ 0  1  0  1 75] [5131.5386]
[ 0  1  0  1 20] [5194.231]
[ 0  2  0  0 90] [5092.5747]
[ 1  0  0  0 80] [5031.0923]
[ 0  1  0  1 20] [5194.231]
[  1   1   0   0 420] [4592.459]
[ 0  1  0  0 40] [5200.648]
[ 0  1  0  0 25] [5217.7466]
[ 0  0  1  1 30] [5495.607]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 40] [5171.434]
[ 0  1  0  0 25] [5217.7466]
[  1   0   0   1 225] [4836.598]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  1 30] [5182.8325]
[ 0  1  0  1 80] [5125.8394]
[ 0  1  0  1 30] [5182.8325]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  0 30] [5212.047]
[ 0  0  1  1 25] [5501.306]
[ 0  1  0  1 20] [5194.231]
[  1   0   0   1 240] [4819.5005]
[  1   0   0   0 105] [5002.596]
[ 0  1  0  1 30] [5182.8325]
[  0   1   0   1 110] [5091.644]
[ 1  0  0  1 60] [5024.6753]
[ 1  0  0  0 75] [5036.7925]
[  1   0   0   0 105] [5002.596]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  0 40] [5200.648]

[ 0  1  0  1 40] [5171.434]
[ 0  1  0  1 50] [5160.0356]
[ 1  0  0  0 75] [5036.7925]
[  1   0   0   0 180] [4917.1064]
[  0   2   0   0 200] [4967.19]
[ 0  1  0  0 70] [5166.4526]
[   1    1    0    0 1660] [3179.033]
[  1   0   0   0 140] [4962.7007]
[ 0  1  0  0 55] [5183.5503]
[  1   0   0   1 150] [4922.088]
[ 0  1  0  0 40] [5200.648]
[ 0  1  0  1 20] [5194.231]
[ 1  0  0  0 75] [5036.7925]
[ 0  0  1  1 20] [5507.0054]
[ 1  0  0  0 75] [5036.7925]
[  1   0   0   1 180] [4887.892]
[ 0  2  0  1 60] [5097.556]
[ 1  0  0  1 60] [5024.6753]
[ 0  0  1  1 20] [5507.0054]
[  1   0   0   0 105] [5002.596]
[  1   0   0   0 195] [4900.009]
[ 0  0  1  1 25] [5501.306]
[ 0  1  0  0 35] [5206.347]
[  0   1   0   1 210] [4977.6577]
[ 0  0  1  1 30] [5495.607]
[  1   1   0   0 240] [4797.6343]
[  0   1   0   0 100] [5132.257]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  0 30] [5212.047]
[ 0  1  0  1 50] [5160.0356]
[ 0  1  0  1 60] [5148.637]
[ 0  1  0  0 45] [5194.9487]
[ 0  1  0  0 35] [5206.347]
[

[ 0  1  0  0 40] [5200.648]
[ 0  0  1  1 40] [5484.2085]
[ 0  1  0  0 55] [5183.5503]
[  0   1   0   0 145] [5080.9634]
[ 0  1  0  0 65] [5172.1523]
[ 0  1  0  0 40] [5200.648]
[  0   1   0   1 220] [4966.2593]
[ 0  1  0  0 55] [5183.5503]
[ 0  1  0  0 35] [5206.347]
[ 0  1  0  0 70] [5166.4526]
[  1   0   0   0 330] [4746.1274]
[  0   1   0   1 100] [5103.0425]
[ 0  1  0  0 60] [5177.851]
[ 0  1  0  0 35] [5206.347]
[  0   1   0   0 285] [4921.383]
[  0   1   0   1 225] [4960.56]
[ 0  1  0  0 40] [5200.648]
[ 0  0  1  1 30] [5495.607]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  1 30] [5182.8325]
[ 0  1  0  1 60] [5148.637]
[ 0  1  0  1 40] [5171.434]
[ 1  0  0  0 85] [5025.393]
[ 0  1  0  0 85] [5149.355]
[ 1  0  0  0 85] [5025.393]
[ 0  0  1  1 25] [5501.306]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  0 30] [5212.047]
[ 0  1  0  1 75] [5131.5386]
[ 0  2  0  0 90] [5092.5747]
[ 0  0  1  1 20] [5507.0054]
[

[ 1  0  0  0 75] [5036.7925]
[ 0  1  0  1 60] [5148.637]
[ 0  1  0  1 60] [5148.637]
[  0   1   0   1 105] [5097.3433]
[ 1  0  0  0 75] [5036.7925]
[ 1  0  0  0 75] [5036.7925]
[ 1  0  0  0 75] [5036.7925]
[ 0  1  0  1 75] [5131.5386]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 75] [5131.5386]
[  1   1   0   1 180] [4836.811]
[ 0  1  0  1 30] [5182.8325]
[ 0  0  1  1 20] [5507.0054]
[ 0  2  0  1 60] [5097.556]
[ 0  1  0  1 30] [5182.8325]
[ 1  0  0  0 75] [5036.7925]
[ 0  1  0  1 20] [5194.231]
[  0   1   0   1 105] [5097.3433]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 60] [5148.637]
[ 0  0  1  1 20] [5507.0054]
[ 0  0  1  1 20] [5507.0054]
[  0   1   0   1 110] [5091.644]
[ 0  0  1  1 40] [5484.2085]
[  1   0   0   0 185] [4911.407]
[  0   1   0   1 180] [5011.8535]
[ 0  1  0  0 50] [5189.25]
[  0   1   0   1 225] [4960.56]
[ 0  0  1  1 35] [5489.9077]
[ 0  0  1  1 35] [5489.9077]
[ 0  0  1  1 40] [5484.2085]
[ 0  1  0  1 50] [5160.0356]
[ 0  0  1  1 30] [5495.

[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  0 25] [5217.7466]
[ 0  2  0  1 60] [5097.556]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 20] [5194.231]
[ 0  1  0  1 60] [5148.637]
[ 0  1  0  1 20] [5194.231]
[ 0  2  0  0 70] [5115.3716]
[ 0  1  0  0 30] [5212.047]
[ 0  1  0  1 20] [5194.231]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  1 20] [5194.231]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  0 40] [5200.648]
[ 0  1  0  1 90] [5114.4414]
[ 0  0  1  1 20] [5507.0054]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0  0 25] [5217.7466]
[ 0  1  0 